---
title: "Simulation study"
date: "`r format(Sys.Date(), '%d %B %Y')`"
output: html_notebook
params: 
  k: 10
  h: 1
  rho: .0001
---

***

```{r, include=FALSE}
library(knitr)
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, message=FALSE}
library(tidyverse)
library(CVXR)
theme_set(theme_bw())
source("../../worst_p_star.R")
source("../../calculate_variance.R")
source("../../best_minmax_regret.R")
source("../../F_mat_from_f_vec.R")
```


Parameters of the following example:

- $k=$ `r params$k`
- $h=$ `r params$h`

```{r}
k <- params$k
h <- params$h
rho <- params$rho
postfix <- paste0("k", k, "_h", h)
df_sim <- readRDS(paste0("../../clean-data/", postfix, "_df_sim", ".rds"))
```


```{r}
var_under_distribution_p <- function(df, p_vec) {
  # input:
  #     df (dataframe) w/ columns:
  #       $id_l
  #       $pi_l
  #       $id_t
  #       $pi_t
  #       $F_mat
  #     p_vec (dbl vec) distribution of a star
  # output:
  #     (dataframe) w/ columns of df plus:
  #       $var_is
  #       $var_f
  df <- df %>% 
    mutate(
      pstar = list(p_vec)
    )
  
  out <- df %>% 
    mutate(
      var_f = pmap_dbl(
        list(pi_l, pi_t, pstar, F_mat),
        function(pi_l, pi_t, pstar, F_mat) {
          calculate_variance(pi_l = pi_l, 
                             pi_t = pi_t, 
                             p_astar = pstar, 
                             F_mat = F_mat, 
                             imp_sam = F)
        }
      )
    )
  return(out)
}
```

<br>

## Worst-case variance of f

```{r}
df_weights <- df_sim
```

```{r}
df_weights <- df_weights %>% 
  mutate(
    optm_rslt = map2(
      pi_l, 
      pi_t, 
      ~best_minmax_regret(.x, .y, rho = rho)
    )
  )

df_weights <- df_weights %>% 
  mutate(
    f0_vec = map(optm_rslt, ~.x$f[1:k, 1]),
    f1_vec = map(optm_rslt, ~.x$f[(k+1):(2*k), 1]),
    F_mat = map2(f1_vec, f0_vec, ~F_mat_from_f_vec(.x, .y))
  )

df_weights <- df_weights %>% 
  mutate(
    pstar_f = pmap(
      list(pi_l, pi_t, F_mat),
      function(pi_l, pi_t, F_mat) {
        worst_p_star(pi_l = pi_l, pi_t = pi_t, F_mat = F_mat, imp_sam = F)
      }
    ),
    var_f = pmap_dbl(
      list(pi_l, pi_t, pstar_f, F_mat),
      function(pi_l, pi_t, pstar_f, F_mat) {
        calculate_variance(pi_l = pi_l, 
                           pi_t = pi_t, 
                           p_astar = pstar_f, 
                           F_mat = F_mat, 
                           imp_sam = F)
      }
    )
  )
```

<br>

## var under uniform distribution


```{r}
df <- df_weights %>% 
  select(id_l, pi_l, id_t, pi_t, F_mat)

df_astar_dist <- df_sim %>% 
  filter(id_t == 0) %>% 
  select(id_l, pi_l) %>% 
  rename(
    id = id_l, 
    p = pi_l
  )

df_fixed_astar <- vector("list", nrow(df_astar_dist))

for (i in 1:nrow(df_astar_dist)) {
  p_vec <- df_astar_dist$p[[i]]
  
  df_fixed_astar[[i]] <- var_under_distribution_p(
    df = df, 
    p_vec = p_vec
  ) %>% 
    mutate(id = df_astar_dist$id[[i]])
}

df_fixed_astar <- bind_rows(df_fixed_astar)
```


```{r}
saveRDS(
  df_weights,
  paste0("../../clean-data/", 
         postfix,
         "_df_mmregret_", 
         str_replace(rho, "\\.", "-"), 
         ".rds")
)

saveRDS(
  df_fixed_astar,
  paste0("../../clean-data/", 
         postfix,
         "_mmregret_fixed_astar_", 
         str_replace(rho, "\\.", "-"), 
         ".rds")
)
```

